import { Routes } from '@angular/router';
import { authGuard, roleGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: '',                          loadComponent: () => import('./features/accueil/accueil.component').then((module) => module.AccueilComponent) },
  { path: 'login',                     loadComponent: () => import('./features/login/login.component').then((module) => module.LoginComponent) },
  { path: 'forgot-password',           loadComponent: () => import('./features/forgot-password/forgot-password.component').then((module) => module.ForgotPasswordComponent) },
  { path: 'reset-password',            loadComponent: () => import('./features/reset-password/reset-password.component').then((module) => module.ResetPasswordComponent) },
  { path: 'admin',                     redirectTo: 'admin/dashboard', pathMatch: 'full' },
  { path: 'admin/dashboard',           loadComponent: () => import('./features/admin/dashboard/dashboard.component').then((module) => module.AdminDashboardComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/profil',              loadComponent: () => import('./features/admin/profil/profil.component').then((module) => module.AdminProfilComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/collaborateurs',            loadComponent: () => import('./features/admin/collaborateurs/liste/liste.component').then((module) => module.ListeCollaborateursComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/collaborateurs/nouveau',    loadComponent: () => import('./features/admin/collaborateurs/formulaire/formulaire.component').then((module) => module.FormulaireCollaborateurComponent), canActivate: [authGuard, roleGuard(['ADMIN', 'MANAGER'])] },
  { path: 'admin/collaborateurs/edit/:id',   loadComponent: () => import('./features/admin/collaborateurs/formulaire/formulaire.component').then((module) => module.FormulaireCollaborateurComponent), canActivate: [authGuard, roleGuard(['ADMIN', 'MANAGER'])] },
  { path: 'admin/projets',                   loadComponent: () => import('./features/admin/projets/liste/liste.component').then((module) => module.ListeProjetsComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/projets/nouveau',           loadComponent: () => import('./features/admin/projets/formulaire/formulaire.component').then((module) => module.FormulaireProjetComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/projets/edit/:id',          loadComponent: () => import('./features/admin/projets/formulaire/formulaire.component').then((module) => module.FormulaireProjetComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/notifications',             loadComponent: () => import('./features/admin/notifications/notifications-page.component').then((m) => m.AdminNotificationsPageComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/rapports',                  loadComponent: () => import('./features/admin/rapports/rapports.component').then((m) => m.AdminRapportsComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/parametres',                loadComponent: () => import('./features/admin/parametres/parametres.component').then((m) => m.AdminParametresComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/roles',                     loadComponent: () => import('./features/admin/roles/roles.component').then((m) => m.AdminRolesComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'admin/affectations',              redirectTo: 'manager/affectation', pathMatch: 'full' },
  { path: 'admin/audit',                      loadComponent: () => import('./features/admin/audit/audit.component').then((m) => m.AdminAuditComponent), canActivate: [authGuard, roleGuard(['ADMIN'])] },
  { path: 'manager',                   redirectTo: 'manager/dashboard', pathMatch: 'full' },
  { path: 'manager/dashboard',         loadComponent: () => import('./features/manager/dashboard/dashboard.component').then((module) => module.ManagerDashboardComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/profil',            loadComponent: () => import('./features/manager/profil/profil.component').then((module) => module.ManagerProfilComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/projets',                 loadComponent: () => import('./features/manager/projets/liste/liste.component').then((module) => module.ManagerListeProjetsComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/projets/nouveau',         loadComponent: () => import('./features/manager/projets/formulaire/formulaire.component').then((module) => module.ManagerFormulaireProjetComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/projets/edit/:id',        loadComponent: () => import('./features/manager/projets/formulaire/formulaire.component').then((module) => module.ManagerFormulaireProjetComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/projets/:id',             loadComponent: () => import('./features/manager/detail-projet/detail-projet.component').then((module) => module.ManagerDetailProjetComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/detail-projet/:id',       loadComponent: () => import('./features/manager/detail-projet/detail-projet.component').then((module) => module.ManagerDetailProjetComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/planning',                redirectTo: 'manager/charge-travail', pathMatch: 'full' },
  { path: 'manager/collaborateurs',         loadComponent: () => import('./features/manager/collaborateurs/collaborateurs.component').then((module) => module.ManagerCollaborateursComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/affectations-en-cours',   loadComponent: () => import('./features/manager/affectations-en-cours/affectations-en-cours.component').then((module) => module.ManagerAffectationsEnCoursComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/affectations/:id/edit',   loadComponent: () => import('./features/manager/affectations/formulaire/formulaire.component').then((module) => module.ManagerFormulaireAffectationComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/charge-travail',          loadComponent: () => import('./features/manager/charge-travail/charge-travail.component').then((module) => module.ManagerChargeTravailComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/historique-affectations', loadComponent: () => import('./features/manager/historique-affectations/historique-affectations.component').then((module) => module.ManagerHistoriqueAffectationsComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/notifications',           loadComponent: () => import('./features/manager/notifications/notifications.component').then((module) => module.ManagerNotificationsPageComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'manager/recommandations',         redirectTo: 'manager/affectation', pathMatch: 'full' },
  { path: 'manager/affectation',             loadComponent: () => import('./features/manager/affectation/resultats/resultats.component').then((module) => module.ManagerResultatsComponent), canActivate: [authGuard, roleGuard(['MANAGER'])] },
  { path: 'mon-profil',                loadComponent: () => import('./features/collaborateurs/profil/profil.component').then((module) => module.CollaborateurProfilComponent), canActivate: [authGuard, roleGuard(['COLLAB'])] },
  { path: 'collaborateurs/dashboard',  loadComponent: () => import('./features/collaborateurs/dashboard/dashboard.component').then((module) => module.CollaborateurDashboardComponent), canActivate: [authGuard, roleGuard(['COLLAB'])] },
  { path: 'dashboard',                 redirectTo: 'collaborateurs/dashboard', pathMatch: 'full' },
  { path: 'competences',               redirectTo: 'mon-profil', pathMatch: 'full' },
  { path: 'mes-projets',               loadComponent: () => import('./features/collaborateurs/mes-projets/mes-projets.component').then((module) => module.CollaborateurMesProjetsComponent), canActivate: [authGuard, roleGuard(['COLLAB'])] },
  { path: 'mon-planning',              redirectTo: 'planning', pathMatch: 'full' },
  { path: 'planning',                  loadComponent: () => import('./features/collaborateurs/planning/planning.component').then((module) => module.CollaborateurPlanningComponent), canActivate: [authGuard, roleGuard(['COLLAB'])] },
  { path: 'historique',                loadComponent: () => import('./features/collaborateurs/historique/historique.component').then((module) => module.CollaborateurHistoriqueComponent), canActivate: [authGuard, roleGuard(['COLLAB'])] },
  { path: 'notifications',             loadComponent: () => import('./features/collaborateurs/notifications/notifications-page.component').then((m) => m.CollaborateurNotificationsPageComponent), canActivate: [authGuard, roleGuard(['COLLAB'])] },
  { path: 'collaborateurs',            redirectTo: 'admin/collaborateurs', pathMatch: 'full' },
  { path: 'collaborateurs/nouveau',    redirectTo: 'admin/collaborateurs/nouveau', pathMatch: 'full' },
  { path: 'collaborateurs/edit/:id',   redirectTo: 'admin/collaborateurs/edit/:id' },
  { path: 'projets',                   redirectTo: 'admin/projets', pathMatch: 'full' },
  { path: 'projets/nouveau',           redirectTo: 'admin/projets/nouveau', pathMatch: 'full' },
  { path: 'projets/edit/:id',          redirectTo: 'admin/projets/edit/:id' },
  { path: 'detail-projet/:id',         redirectTo: 'manager/detail-projet/:id' },
  { path: 'affectations-en-cours',     redirectTo: 'manager/affectations-en-cours', pathMatch: 'full' },
  { path: 'charge-travail',            redirectTo: 'manager/charge-travail', pathMatch: 'full' },
  { path: 'historique-affectations',   redirectTo: 'manager/historique-affectations', pathMatch: 'full' },
  { path: 'affectation',               redirectTo: 'manager/affectation', pathMatch: 'full' },
  { path: '**',                        redirectTo: '' },
];